### PR TITLE
Allow printing a prettytable to anything that implements Write

### PR DESCRIPTION
**Pull request by asomers**
For example, stderr instead of stdout.

Depends on https://github.com/phsym/prettytable-rs/pull/156

### CODE REVIEW

**Comment by romankoblov** [comment]
Fails on publish:
```
error[E0277]: the trait bound `W: term::Terminal` is not satisfied
   --> src/text.rs:413:26
    |
413 |         table.print_term(f)
    |               ---------- ^ the trait `term::Terminal` is not implemented for `W`
    |               |
    |               required by a bound introduced by this call
    |
note: required by a bound in `prettytable::Table::print_term`
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prettytable-rs-0.10.0/src/lib.rs:373:26
    |
373 |     pub fn print_term<T: Terminal + ?Sized>(&self, out: &mut T) -> Result<usize, Error> {
    |                          ^^^^^^^^ required by this bound in `Table::print_term`
help: consider further restricting this bound
    |
410 |         where W: std::io::Write + std::io::IsTerminal + term::Terminal
    |                                                       ++++++++++++++++
```

**Comment by asomers** [comment]
What was the command that failed?  And BTW I wouldn't expect `cargo publish` to work since this PR adds a `[patch.crates-io]` section to Cargo.toml.

**Comment by romankoblov** [comment]
`cargo publish` fails, `cargo build` works. Why specific patch then?

**Comment by romankoblov** [comment]
Oh, you changed `prettytable` too. Ok, can you then send another PR when this released, so I can publish new version?

**Comment by asomers** [comment]
Absolutely.

**Pull request merged**
